### ISSUE TITLE
Mensa Südstadt

### ISSUE THREAD

**Issue by greekyoghourt** [cvzi/mensa#54]
The mensa Südstadt in Köln is empty on openmensa https://openmensa.org/c/383 but it is open at the moment see https://www.kstw.de/speiseplan/

**Comment by cvzi** [comment]
I will take a look. Seems like the website that publishes the menu has changed

**Comment by cvzi** [comment]
The website has changed completely. I'll have to rewrite the parser.

**Comment by cvzi** [comment]
I have updated it
